"""add is_active columns to teachers and classrooms

Revision ID: 33d8e40a0696
Revises: 8496821cbaf1
Create Date: 2025-05-13 02:34:52.813544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d8e40a0696'
down_revision = '8496821cbaf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'faculty')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('faculty', sa.TEXT(), nullable=True))
    # ### end Alembic commands ### 