"""fix model class order for relationships

Revision ID: 556d17f4655b
Revises: a72bfb14e08b
Create Date: 2025-05-18 15:32:40.035201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556d17f4655b'
down_revision = 'a72bfb14e08b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 