"""Add course type and category fields

Revision ID: 573d3e6f55ac
Revises: 
Create Date: 2025-05-11 14:30:42.626059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573d3e6f55ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 