"""fix schedule table name and relationships

Revision ID: 6d6965708b37
Revises: c6ad20ed5723
Create Date: 2025-05-18 15:31:44.564161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6965708b37'
down_revision = 'c6ad20ed5723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 