"""add_total_hours_column_to_course

Revision ID: 8496821cbaf1
Revises: f32f02d2000c
Create Date: 2025-05-11 15:32:04.778311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8496821cbaf1'
down_revision = 'f32f02d2000c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('total_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'total_hours')
    # ### end Alembic commands ### 