"""fix schedules relationship in course and classroom

Revision ID: a72bfb14e08b
Revises: 6d6965708b37
Create Date: 2025-05-18 15:32:10.598541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72bfb14e08b'
down_revision = '6d6965708b37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 